version: 2

before:
  hooks:
    - go mod tidy
builds:
  - id: nowly-tree
    binary: nowly-tree
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: 'nowly-tree'
    homepage: https://github.com/nowly-lab/dep-tree
    description: "Nowly Lab's Homebrew distribution of dep-tree."
    license: MIT
    repository:
      owner: nowly-lab
      name: dep-tree
      branch: main
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    skip_upload: false
    test: |
      system "#{bin}/nowly-tree", "--version"
