# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NowlyTree < Formula
  desc "Nowly Lab's Homebrew distribution of dep-tree."
  homepage "https://github.com/nowly-lab/dep-tree"
  version "0.23.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.10/nowly-tree_darwin_amd64.tar.gz"
      sha256 "1872a16fd53f7f6a6c09d440f485321f529aa94900c388042ca1a391b4431d56"

      def install
        bin.install "nowly-tree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.10/nowly-tree_darwin_arm64.tar.gz"
      sha256 "df51b6e4a5de491de0115a1af478cffef6b0b14636b491219d146a326f671059"

      def install
        bin.install "nowly-tree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.10/nowly-tree_linux_amd64.tar.gz"
      sha256 "c018d02df92598efb3ab68c678979a078977da9c594cd2f34bd92d28af6088af"
      def install
        bin.install "nowly-tree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.10/nowly-tree_linux_arm64.tar.gz"
      sha256 "3f8b3e8d89b32091248efa4330d8c6543690894b5c398928d320fd3e3391c1e3"
      def install
        bin.install "nowly-tree"
      end
    end
  end

  test do
    system "#{bin}/nowly-tree", "--version"
  end
end
