# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NowlyTree < Formula
  desc "Nowly Lab's Homebrew distribution of dep-tree."
  homepage "https://github.com/nowly-lab/dep-tree"
  version "0.23.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.5/nowly-tree_darwin_amd64.tar.gz"
      sha256 "19de7f1da71e213543b58ad1f51409a44c47c1e4ebd14a4d6680af32da84aa57"

      def install
        bin.install "nowly-tree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.5/nowly-tree_darwin_arm64.tar.gz"
      sha256 "fcfe0b99ee0fe29d3f4b6e9b8c7aebfd7a573ac5ecfec46dce373264bd9a6450"

      def install
        bin.install "nowly-tree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.5/nowly-tree_linux_amd64.tar.gz"
      sha256 "b606a2ac55461c7d5755bcae4aeeaf3533f89bcb8d7f5174a51295ba59f19722"
      def install
        bin.install "nowly-tree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.5/nowly-tree_linux_arm64.tar.gz"
      sha256 "968f5ee3c47c0e777464e21d09f29d708e3b5662f79ab3f19efacf47989d0ff1"
      def install
        bin.install "nowly-tree"
      end
    end
  end

  test do
    system "#{bin}/nowly-tree", "--version"
  end
end
