# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NowlyTree < Formula
  desc "Nowly Lab's Homebrew distribution of dep-tree."
  homepage "https://github.com/nowly-lab/dep-tree"
  version "0.23.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.7/nowly-tree_darwin_amd64.tar.gz"
      sha256 "db8c18c7b369d4b3c030a5ed04617d719a83e462a10afee88c75a141d91614cb"

      def install
        bin.install "nowly-tree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.7/nowly-tree_darwin_arm64.tar.gz"
      sha256 "84a3973bae2df2f890315a1417ab94cac7d1b3e8130fab4498eb8bac80a544c7"

      def install
        bin.install "nowly-tree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.7/nowly-tree_linux_amd64.tar.gz"
      sha256 "3ff48b0f009dc45714e7b6a577b572e1299e9f3a64c6ebc8ec76507c3af1413a"
      def install
        bin.install "nowly-tree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.7/nowly-tree_linux_arm64.tar.gz"
      sha256 "ef3b04c99ef39e781b58b5b82d557054b36557ab84160c4f67ddbed0b1fc594b"
      def install
        bin.install "nowly-tree"
      end
    end
  end

  test do
    system "#{bin}/nowly-tree", "--version"
  end
end
