# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NowlyTree < Formula
  desc "Nowly Lab's Homebrew distribution of dep-tree."
  homepage "https://github.com/nowly-lab/dep-tree"
  version "0.23.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.7/nowly-tree_darwin_amd64.tar.gz"
      sha256 "69d8c50152ff1b21aff9d8cc191187adecca4cdaf67312079591eccbb01cfa73"

      def install
        bin.install "nowly-tree"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.7/nowly-tree_darwin_arm64.tar.gz"
      sha256 "f7902af393ca6058bf55018a03a37bcdec8309e72e17b180a6ed15675d082c60"

      def install
        bin.install "nowly-tree"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.7/nowly-tree_linux_amd64.tar.gz"
      sha256 "3c3245d8eee1490c9535de0260960a15ea51ae02b290c110f3aab4f0e1b401c1"
      def install
        bin.install "nowly-tree"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nowly-lab/dep-tree/releases/download/v0.23.7/nowly-tree_linux_arm64.tar.gz"
      sha256 "f5854aad6ba6ec983a5de8ceea7b045d914a3ac856a2d5d1c47880d3b0fc8c18"
      def install
        bin.install "nowly-tree"
      end
    end
  end

  test do
    system "#{bin}/nowly-tree", "--version"
  end
end
